# Generated by Django 2.1.4 on 2018-12-25 10:57

from django.db import migrations, models
import django.db.models.deletion
import profiling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(profiling.models.DeviceType(models.CharField(max_length=1000)), models.CharField(max_length=1000)), (profiling.models.DeviceType(models.ManyToManyField(related_name='device_types', to='profiling.Service')), models.ManyToManyField(related_name='device_types', to='profiling.Service'))])),
                ('brand', models.IntegerField(default=0)),
                ('model', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField(default=0)),
                ('beta', models.FloatField(default=0)),
                ('gama', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='profiling.User'),
        ),
    ]
