# Generated by Django 2.1.4 on 2019-01-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_auto_20181225_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lat', models.CharField(max_length=1000)),
                ('long', models.CharField(max_length=1000)),
                ('radius', models.IntegerField(default=0)),
                ('devices', models.ManyToManyField(to='profiling.Device')),
            ],
        ),
    ]
