# Generated by Django 2.1.4 on 2019-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lat',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='long',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='services',
            field=models.ManyToManyField(to='profiling.Service'),
        ),
    ]
