# Generated by Django 2.1.4 on 2019-01-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0004_auto_20190113_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=1000),
        ),
    ]
